export const ALL_IMAGE_ASSETS = [
  // Scene Backgrounds & Main Assets
  "/asset/gedung.png",
  "/asset/lobby.png",
  "/asset/lorong_gallery.png",
  "/asset/gallery.png",
  "/asset/cubit.png",
  "/asset/garden.png",
  "/asset/flower_garden.png",
  "/asset/patung.png",
  "/asset/patung_minigame.png",
  "/asset/stay.png",
  "/asset/kasih_bunga.png",
  "/asset/peluk.png",

  // Character Sprites - Aii
  "/char/aii/aii.png",
  "/char/aii/bingung.png",
  "/char/aii/kaget.png",
  "/char/aii/kawatir.png",
  "/char/aii/kesel.png",
  "/char/aii/ketawa.png",
  "/char/aii/malu.png",
  "/char/aii/marah.png",
  "/char/aii/nangis.png",
  "/char/aii/ngomong.png",
  "/char/aii/ngomong_senyum.png",
  "/char/aii/salting.png",
  "/char/aii/sedih.png",
  "/char/aii/semangat.png",
  "/char/aii/senyum.png",
  "/char/aii/terharu.png",
  "/char/aii/terharu_bahagia.png",

  // Character Sprites - Kibo
  "/char/kibo/bercanda.png",
  "/char/kibo/bingung.png",
  "/char/kibo/kaget.png",
  "/char/kibo/kawatir.png",
  "/char/kibo/ketawa.png",
  "/char/kibo/kibo.png",
  "/char/kibo/malu.png",
  "/char/kibo/marah.png",
  "/char/kibo/nangis.png",
  "/char/kibo/ngomong.png",
  "/char/kibo/ngomong_senyum.png",
  "/char/kibo/salting.png",
  "/char/kibo/sedih.png",
  "/char/kibo/semangat.png",
  "/char/kibo/senyum.png",
  "/char/kibo/takut.PNG",

  // Character Sprites - Petugas
  "/char/petugas/petugas.png",

  // Flower Minigame Assets
  "/flower/dahlia_pink.png",
  "/flower/dahlia_putih.png",
  "/flower/dahlia_ungu.png",
  "/flower/kotak_dahlia_pink.png",
  "/flower/kotak_dahlia_putih.png",
  "/flower/kotak_dahlia_ungu.png",
  "/flower/kotak_lavender.png",
  "/flower/kotak_mawar_merah.png",
  "/flower/kotak_mawar_pink.png",
  "/flower/kotak_mawar_putih.png",
  "/flower/kotak_sunflower.png",
  "/flower/kotak_tulip_kuning.png",
  "/flower/kotak_tulip_pink.png",
  "/flower/kotak_tulip_putih.png",
  "/flower/kotak_tulip_ungu.png",
  "/flower/krisan.png",
  "/flower/lavender.png",
  "/flower/mawar_merah.png",
  "/flower/mawar_pink.png",
  "/flower/mawar_putih.png",
  "/flower/peakok.png",
  "/flower/sunflower.png",
  "/flower/tulip_kuning.png",
  "/flower/tulip_pink.png",
  "/flower/tulip_putih.png",
  "/flower/tulip_ungu.png",

  // Gallery Paintings
  "/lukisan/lukisan_1.jpeg",
  "/lukisan/lukisan_2.jpeg",
  "/lukisan/lukisan_3.jpeg",

  // Statue Minigame Pieces
  "/patung/patung_batu.png",
  "/patung/patung_hati.png",
  "/patung/patung_tangan.png",
];

export const ALL_AUDIO_ASSETS = [
  "/audio/foot_steps.mp3",
  "/audio/bgm/cyht.mp3",
  "/audio/bgm/ilmlou.mp3",
  "/audio/bgm/mcimy.mp3",
  "/audio/bgm/ollg.mp3",
  "/audio/bgm/stars.mp3",
];
